"""
Simulated notification system for Heatwatch demo.

In production, this would integrate with:
- Twilio (SMS to coaches/parents)
- Google Calendar API (update practice schedules)
- SendGrid (email to athletic directors)
- Slack webhook (team channels)

For hackathon demo, generates the structured requests that would be sent.
"""

import json
from datetime import datetime, timedelta


def generate_sms(coach_name: str, school: str, site_id: str,
                 original_time: str, new_time: str, temp_f: float,
                 policy_level: str, action: str) -> dict:
    """Generate an SMS notification draft for a coach."""
    if action == "RESCHEDULE":
        message = (
            f"HEATWATCH: {school} practice moved from {original_time} to {new_time}. "
            f"Forecast temp at original time: {temp_f:.0f}°F ({policy_level.upper()} level). "
            f"Safer window identified. Reply CONFIRM or call AD."
        )
    elif action == "SUSPEND":
        message = (
            f"HEATWATCH: {school} practice at {original_time} CANCELLED. "
            f"Forecast temp: {temp_f:.0f}°F ({policy_level.upper()} level). "
            f"No safe alternative found today. Indoor option or reschedule to tomorrow."
        )
    else:
        message = (
            f"HEATWATCH: {school} practice at {original_time} — conditions safe. "
            f"Temp: {temp_f:.0f}°F ({policy_level.upper()}). Proceed as planned."
        )

    return {
        "channel": "sms",
        "to": f"+1 (480) XXX-{hash(site_id) % 9000 + 1000}",
        "recipient": coach_name,
        "role": "Head Coach",
        "school": school,
        "message": message,
        "message_length": len(message),
        "status": "draft",
        "timestamp": datetime.now().isoformat(),
    }


def generate_calendar_event(school: str, site_id: str,
                            original_time: str, new_time: str,
                            date: str, action: str) -> dict:
    """Generate a calendar event update request."""
    if action == "RESCHEDULE":
        return {
            "service": "google_calendar",
            "action": "update",
            "event_title": f"{school} Football Practice",
            "date": date,
            "original_time": original_time,
            "new_time": new_time,
            "duration_hours": 2.5,
            "location": f"{school} Football Field",
            "description": (
                f"Rescheduled by Heatwatch agent.\n"
                f"Reason: Heat safety — original time exceeded policy threshold.\n"
                f"Decision timestamp: {datetime.now().isoformat()}"
            ),
            "status": "draft",
        }
    elif action == "SUSPEND":
        return {
            "service": "google_calendar",
            "action": "cancel",
            "event_title": f"{school} Football Practice",
            "date": date,
            "original_time": original_time,
            "reason": "Heat safety — no safe alternative found today",
            "status": "draft",
        }
    else:
        return {
            "service": "google_calendar",
            "action": "no_change",
            "event_title": f"{school} Football Practice",
            "date": date,
            "time": original_time,
            "status": "confirmed",
        }


def generate_athletic_director_email(school: str, decisions: list) -> dict:
    """Generate an email summary for the athletic director."""
    n_reschedule = sum(1 for d in decisions if d["action"] == "RESCHEDULE")
    n_suspend = sum(1 for d in decisions if d["action"] == "SUSPEND")
    n_ok = sum(1 for d in decisions if d["action"] == "PROCEED")

    body_lines = [
        f"Heatwatch Daily Report — {datetime.now().strftime('%B %d, %Y')}",
        f"",
        f"Summary: {n_ok} safe, {n_reschedule} rescheduled, {n_suspend} suspended",
        f"",
        f"Details:",
    ]

    for d in decisions:
        status_icon = {"PROCEED": "✓", "RESCHEDULE": "→", "SUSPEND": "✗"}.get(d["action"], "?")
        reason = d.get('reason', d.get('policy_level', '').upper())
        body_lines.append(
            f"  {status_icon} {d['site_name']}: {d['action']} — {reason}"
        )

    body_lines.extend([
        f"",
        f"Audit trail: {len(decisions)} records committed to hash-chained log.",
        f"This report was auto-generated by Heatwatch.",
    ])

    return {
        "service": "sendgrid",
        "action": "send",
        "to": f"athletic.director@{school.lower().replace(' ', '')}.edu",
        "subject": f"Heatwatch: {n_reschedule + n_suspend} practice changes needed today",
        "body": "\n".join(body_lines),
        "status": "draft",
    }


def generate_all_notifications(schedule: list) -> dict:
    """Generate all notifications for a set of practice schedule decisions.

    Args:
        schedule: list of dicts with site_name, site_id, original_time,
                  new_time, temp_f, policy_level, action, date

    Returns:
        dict with sms, calendar, email lists
    """
    sms_messages = []
    calendar_events = []
    emails_by_ad = {}

    for entry in schedule:
        school = entry["site_name"]
        site_id = entry["site_id"]

        # SMS to coach
        sms = generate_sms(
            coach_name=f"Coach ({school})",
            school=school,
            site_id=site_id,
            original_time=entry["original_time"],
            new_time=entry.get("new_time", entry["original_time"]),
            temp_f=entry["temp_f"],
            policy_level=entry["policy_level"],
            action=entry["action"],
        )
        sms_messages.append(sms)

        # Calendar event
        cal = generate_calendar_event(
            school=school,
            site_id=site_id,
            original_time=entry["original_time"],
            new_time=entry.get("new_time", entry["original_time"]),
            date=entry["date"],
            action=entry["action"],
        )
        calendar_events.append(cal)

        # Group by AD for email
        ad_key = school
        if ad_key not in emails_by_ad:
            emails_by_ad[ad_key] = []
        emails_by_ad[ad_key].append(entry)

    # Generate AD emails
    emails = []
    for school, entries in emails_by_ad.items():
        email = generate_athletic_director_email(school, entries)
        emails.append(email)

    return {
        "sms": sms_messages,
        "calendar": calendar_events,
        "emails": emails,
        "total_notifications": len(sms_messages) + len(calendar_events) + len(emails),
    }
